/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as MemoriesRouteImport } from './routes/memories'
import { Route as MyContextRouteImport } from './routes/my-context'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents.$documentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesRoute = MemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => rootRouteImport,
} as any)
const MyContextRoute = MyContextRouteImport.update({
  id: '/my-context',
  path: '/my-context',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/$documentId',
  path: '/$documentId',
  getParentRoute: () => DocumentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/graph': typeof GraphRoute
  '/memories': typeof MemoriesRoute
  '/my-context': typeof MyContextRoute
  '/settings': typeof SettingsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/graph': typeof GraphRoute
  '/memories': typeof MemoriesRoute
  '/my-context': typeof MyContextRoute
  '/settings': typeof SettingsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/connections': typeof ConnectionsRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/graph': typeof GraphRoute
  '/memories': typeof MemoriesRoute
  '/my-context': typeof MyContextRoute
  '/settings': typeof SettingsRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/connections'
    | '/documents'
    | '/graph'
    | '/memories'
    | '/my-context'
    | '/settings'
    | '/documents/$documentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/connections'
    | '/documents'
    | '/graph'
    | '/memories'
    | '/my-context'
    | '/settings'
    | '/documents/$documentId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/connections'
    | '/documents'
    | '/graph'
    | '/memories'
    | '/my-context'
    | '/settings'
    | '/documents/$documentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  ConnectionsRoute: typeof ConnectionsRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  GraphRoute: typeof GraphRoute
  MemoriesRoute: typeof MemoriesRoute
  MyContextRoute: typeof MyContextRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories': {
      id: '/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof MemoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-context': {
      id: '/my-context'
      path: '/my-context'
      fullPath: '/my-context'
      preLoaderRoute: typeof MyContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  ConnectionsRoute: ConnectionsRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  GraphRoute: GraphRoute,
  MemoriesRoute: MemoriesRoute,
  MyContextRoute: MyContextRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
